// Public foundation API. Future runtime composition belongs at this boundary.
export * from './appointments/models.js';
export * from './appointments/lifecycle.js';
export * from './clinic/models.js';
export * from './config/index.js';
export * from './patients/models.js';
export * from './scheduling/models.js';
export * from './shared/types.js';
export * from './ports/repositories.js';
export * from './ports/messaging.js';
export * from './ports/runtime.js';
export * from './shared/errors.js';
export * from './clinic/validation.js';
export * from './scheduling/availability.js';
export * from './appointments/service.js';
export * from './queue/order.js';
export * from './ports/projection.js';
export * from './projection/sheets.js';
export * from './scheduling/capacity.js';
